Allow to specify match level
wix-incubator/match-screenshot pull request #38
Opened 2019-02-12 10:18 UTC by michabeeri

2019-02-13 14:17 UTC, yanivefraim requested changes

2019-02-13 14:17 UTC, yanivefraim commented on lib/toMatchEyesScreenshot.js
> +    eyes.setMatchLevel(matchLevel || MatchLevel.Strict);
This change might break some projects, because setting 'MatchLevel' can be done via Applitools UI. In this case, if I changed my match level on Applitools UI (let's say that I'm using "Exact", for example), after this change I will override it with default "Strict", because I didn't send anything via match-screenshot api...

One approach for fixing this will be to call `eyes.setMatchLevel(...` only in case we have a match level argument.

2019-02-13 14:17 UTC, yanivefraim commented on matchLevel.js
> +module.exports = require('eyes.images').MatchLevel;
what is the reason for using this helper (we are using it only in one place)?

2019-02-13 14:19 UTC, yanivefraim commented
Thanks for the PR! Looks great. Please look at my comments.
Plus, I played with the PR locally and made a new baseline, by mistake. Can you please change the value of the key for the new test? (let's say - `helloWorldWithMatchLevelExact`)

2019-02-13 17:56 UTC, michabeeri commented on lib/toMatchEyesScreenshot.js
> +    eyes.setMatchLevel(matchLevel || MatchLevel.Strict);
Agreed, will change !

2019-02-13 17:57 UTC, michabeeri commented on matchLevel.js
> +module.exports = require('eyes.images').MatchLevel;
This is for the users of matchScreenshot, so they don't have to require eyes directly

2019-02-13 19:40 UTC, yanivefraim commented on matchLevel.js
> +module.exports = require('eyes.images').MatchLevel;
oh, got it. I would add this to the readme as well (otherwise users won't know to use it)

2019-02-13 23:47 UTC, michabeeri commented on matchLevel.js
> +module.exports = require('eyes.images').MatchLevel;
added some usage example

2019-02-14 07:46 UTC, yanivefraim approved these changes

2019-02-14 07:47 UTC, merged